package dev.l3g7.griefer_utils.misc.mxparser.parsertokens;

import dev.l3g7.griefer_utils.misc.mxparser.mXparser;
public final class Operator {
	public static final int TYPE_ID 				= 1;
	public static final String TYPE_DESC			= "Operator";
	public static final int PLUS_ID 				= 1;
	public static final int MINUS_ID 				= 2;
	public static final int MULTIPLY_ID 			= 3;
	public static final int DIVIDE_ID 				= 4;
	public static final int POWER_ID 				= 5;
	public static final int FACT_ID					= 6;
	public static final int MOD_ID					= 7;
	public static final int PERC_ID					= 8;
	public static final int TETRATION_ID			= 9;
	public static final String PLUS_STR 			= "+";
	public static final String MINUS_STR 			= "-";
	public static final String MULTIPLY_STR 		= "*";
	public static final String DIVIDE_STR 			= "/";
	public static final String POWER_STR 			= "^";
	public static final String FACT_STR 			= "!";
	public static final String MOD_STR				= "#";
	public static final String PERC_STR				= "%";
	public static final String TETRATION_STR		= "^^";
	public static final String PLUS_SYN 			= "a + b";
	public static final String MINUS_SYN 			= "a - b";
	public static final String MULTIPLY_SYN 		= "a * b";
	public static final String DIVIDE_SYN 			= "a / b";
	public static final String POWER_SYN 			= "a^b";
	public static final String FACT_SYN 			= "n!";
	public static final String MOD_SYN				= "a # b";
	public static final String PERC_SYN				= "n%";
	public static final String TETRATION_SYN		= "a^^n";
	public static final String PLUS_DESC 			= "Addition";
	public static final String MINUS_DESC 			= "Subtraction";
	public static final String MULTIPLY_DESC 		= "Nultiplication";
	public static final String DIVIDE_DESC 			= "Division";
	public static final String POWER_DESC 			= "Exponentiation";
	public static final String FACT_DESC			= "Factorial";
	public static final String MOD_DESC				= "Modulo function";
	public static final String PERC_DESC			= "Percentage";
	public static final String TETRATION_DESC		= "Tetration (hyper-4, power tower, exponential tower)";
	public static final String PLUS_SINCE 			= mXparser.NAMEv10;
	public static final String MINUS_SINCE 			= mXparser.NAMEv10;
	public static final String MULTIPLY_SINCE 		= mXparser.NAMEv10;
	public static final String DIVIDE_SINCE 		= mXparser.NAMEv10;
	public static final String POWER_SINCE 			= mXparser.NAMEv10;
	public static final String FACT_SINCE			= mXparser.NAMEv10;
	public static final String MOD_SINCE			= mXparser.NAMEv10;
	public static final String PERC_SINCE			= mXparser.NAMEv41;
	public static final String TETRATION_SINCE		= mXparser.NAMEv42;
}
